apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookstore-broker
  namespace: bookstore-broker
  labels:
    run: bookstore-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bookstore-broker
  template:
    metadata:
      labels:
        run: bookstore-broker
    spec:
      containers:
      - image: sample/bookstore-service-broker:0.0.1.BUILD-SNAPSHOT
        name: bookstore-broker
        ports:
        - containerPort: 8080
