apiVersion: v1
kind: Service
metadata:
  name: bookstore-broker
  namespace: service-catalog
  labels:
    run: bookstore-broker
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    run: bookstore-broker
  type: LoadBalancer