apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: bookstore-broker
  labels:
    run: bookstore-broker
spec:
  url: http://35.197.249.208
  authInfo:
    basic:
      secretRef:
        name: bookstore-broker-secret
        namespace: service-catalog

